name: Demo VM Setup

on: 
  push:
    branches:
      - contabo-vm-setup
    
jobs:
  setup_demo_vm:
    strategy:
      matrix:
        go-version: [1.23.x]
    name: Deploy to demo
    runs-on: ubuntu-latest

    steps:
      - name: Setup Contabo VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami

            sudo dnf update -y

            # Install Docker if it's not already installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo dnf install -y yum-utils
              sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
              sudo dnf install -y docker-ce docker-ce-cli containerd.io
            else
              echo "Docker is already installed."
            fi

            sudo systemctl enable docker
            sudo systemctl start docker

            docker --version